version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SVC_NAME: 'demo1'
      SVC_ENV: 'local'
      SVC_PORT: '4567'
      CLOUDTRUTH_API_KEY: ${CLOUDTRUTH_API_KEY:-}
      AWS_DEFAULT_REGION: 'local'
    ports:
      - 4567:4567
    volumes:
      - .:/srv/app
