name: CD

on: [push]

env:
  CT_API_KEY: ${{ secrets.CT_API_KEY }}

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup operation environment
        run: |
          branch=${GITHUB_REF##*/}
          if [[ "$branch" == "master" ]]; then
            env="production"
          else
            env="development"
          fi
          echo "ENV=${env}" >> $GITHUB_ENV

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install cloudtruth cli
        run: |
          # Temporarily in s3 till we publish https://github.com/cloudtruth/cloudtruth-cli
          curl https://ctdemo-development-sample-data.s3.amazonaws.com/bin/cloudtruth -o /tmp/cloudtruth
          chmod +x /tmp/cloudtruth

      - name: Install Atmos
        run: gem install --no-document simplygenius-atmos

      - name: Setup Atmos
        run: |
          mkdir -p config
          /tmp/cloudtruth -e ${ENV} template get atmos_yml > config/atmos.yml

      - name: Build the Docker image
        run: |
          /tmp/cloudtruth -e ${ENV} template get deploy.service_dotenv  > .env
          docker build . --file Dockerfile --tag demo1

      - name: Deploy to ECS
        run: |
          source <(/tmp/cloudtruth -e ${ENV} template get deploy.aws_credentials_env)
          atmos -e ${ENV} container deploy -c ctdemo-${ENV}-services -i demo1 ctdemo-${ENV}-demo1
