name: CD

on: [push]

env:
  CLOUDTRUTH_API_KEY: ${{ secrets.CLOUDTRUTH_API_KEY }}

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup operation environment
        run: |
          branch=${GITHUB_REF##*/}
          if [[ "$branch" == "master" ]]; then
            env="production"
          else
            env="development"
          fi
          echo "ENV=${env}" >> $GITHUB_ENV

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install cloudtruth cli
        uses: cloudtruth/cli-action@v1

      - uses: cloudtruth/configure-action@v1
        with:
          token: "${{ secrets.CLOUDTRUTH_API_KEY }}"
          project: "deploy"
          environment: "${{ env.ENV }}"
          overwrite: true

      - name: Install Atmos
        run: gem install --no-document simplygenius-atmos

      - name: Setup Atmos
        run: |
          mkdir -p config
          echo -e "${ATMOS_YML}" > config/atmos.yml

      - name: Build the Docker image
        run: |
          # One could use cloudtruth to update .env like so:
          #   cloudtruth -e ${ENV} template get deploy.service_dotenv  > .env
          # But we are using "cloudtruth run" in entrypoint.sh to fetch most
          # current data into the process environment at startup time
          #
          docker build . --file Dockerfile --tag demo1

      - name: Ensure cloudtruth contains all the parameters defined in .env
        run: |
          docker run -e CLOUDTRUTH_API_KEY=${CLOUDTRUTH_API_KEY} -e SVC_ENV=default demo1 ctsync

      - name: Deploy to ECS
        run: |
          atmos -e ${ENV} container deploy -c ctdemo-${ENV}-services -i demo1 ctdemo-${ENV}-demo1

      - name: Install kubectl
        run: |
          curl -Lsf https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl -o /tmp/kubectl
          chmod +x /tmp/kubectl

      - name: Deploy to EKS
        run: |
          # Update configmap
          cloudtruth -e ${ENV} --project service-demo2 template get configmap | \
            /tmp/kubectl --kubeconfig=<(echo "$KUBE_CFG") apply -f -

          # Apply deployment yml
          cloudtruth -e ${ENV} --project deploy template get service_demo2_kube_yml | \
            /tmp/kubectl --kubeconfig=<(echo "$KUBE_CFG") apply -f -
